### ISSUE TITLE
All volumes are being created in nurnberg locations. 

### ISSUE THREAD

**Issue by madfromplay** [stevenklar/kubernetes-hetzner-storage#3]
Hello!
https://github.com/stevenklar/kubernetes-hetzner-storage/blob/master/pkg/provisioner/provision.go have a hardcoded nurnberg location. 

Due to hetzner restrictions you can't mount volumes from another DC. 
Could you please add nother parameted to config map so we can create volumes in same location with k8s cluster? 
Thanks in advance.

**Comment by stevenklar** [comment]
Will have a look into it soon. As volumes is out of beta meanwhile your'e right.

**Comment by anebi** [comment]
Hi @stevenklar ,

May I ask you to have a look at this issue if you have time for it? :)

Hetzner volumes are no longer beta.

Thanks and regards,
Ali Nebi

**Comment by stevenklar** [comment]
Hey @anebi 

for sure I will have time in the next couple of days and will add location + size support.
Thank you for this friendly reminder!

Regards
-stevenklar
